#98 auth class を hooks で置き換え
afes-website/cappuccino-app pull request #103
Opened 2021-07-19 16:00 UTC by su8ru

close #98

めっちゃ大変だった
見つけきれてないバグがあるかも、auth 周りいろいろポチポチしてみてね

2021-07-20 14:41 UTC, Takeno-hito submitted a review, later dismissed

2021-07-23 08:43 UTC, ibuki2003 requested changes

2021-07-23 08:43 UTC, ibuki2003 commented on src/App.tsx
> +  const [authState, authDispatch] = useAuthProvideValue(() => {
(Slackに書いちゃったけど) ここでauthState/authDispatchを管理するのしっくり来なさがあり callbackだけここに置いてAuthProviderコンポーネントに渡す みたいな実装にすると綺麗な気がしました

2021-07-23 08:43 UTC, ibuki2003 commented on src/libs/auth/useVerifyPermission.ts
> +export const useVerifyPermission = (
名前、verifyというよりrequireとかにしたくないですか

2021-07-23 08:43 UTC, ibuki2003 commented on src/pages/Login.tsx
> +          switchCurrentUser(id);
registerUserにその機能はついています どっちかに

2021-07-23 14:23 UTC, Takeno-hito approved these changes

2021-07-23 14:35 UTC, ibuki2003 approved these changes

2021-07-23 14:35 UTC, merged