#123 スキャン時に効果音を鳴らす
afes-website/cappuccino-app pull request #124
Opened 2021-08-18 16:52 UTC by su8ru

close #123

正確には ResultChip 発火時なので API 通信後

- autoplay の問題: [メディアおよびウェブオーディオ API の自動再生ガイド \- Web メディア技術 \| MDN](https://developer.mozilla.org/ja/docs/Web/Media/Autoplay_guide)
- 対策参考: [Safari で音声、動画を再生する際に発生する NotAllowedError に対応する方法 \| 滋賀／京都／大阪でホームページ制作ならYUKiYURi WEB](https://yukiyuriweb.com/2021/03/12/how-to-handle-notallowederror-in-safari/#NotAllowedError-2)

2021-09-06 23:40 UTC, Takeno-hito reviewed
コードは問題ないと思うけどerrorの音、エラーっぽくない気がする エラーの音の高さを少しずつ下げてくとかした方が良い気がする

2021-09-07 06:36 UTC, su8ru commented
> @Takeno-hito コードは問題ないと思うけどerrorの音、エラーっぽくない気がする エラーの音の高さを少しずつ下げてくとかした方が良い気がする

なんかいい感じの探してきて

https://soundeffect-lab.info/sound/button/
http://www.kurage-kosho.info/system.html

2021-09-07 07:44 UTC, ibuki2003 requested changes

2021-09-07 07:44 UTC, ibuki2003 commented on src/libs/audio.ts
> +document.documentElement.addEventListener("click", init);
ドキュメント読み込み完了の用途にはonloadイベントをぜひご活用ください

2021-09-07 07:44 UTC, ibuki2003 commented on src/libs/audio.ts
> +document.documentElement.addEventListener("click", init);
https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener
onceオプションのご用意がございます ご査収ください

2021-09-07 07:44 UTC, ibuki2003 commented on src/libs/audio.ts
> +      audio.play();
preloadプロパティのご用意がございます
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video#attr-preload
ご不満でしたらloadメソッドもございますのでご検討ください
https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/load

2021-09-07 07:44 UTC, ibuki2003 commented on src/components/ResultChip.tsx
> +            successAudio.currentTime = 0;
最初から再生にはloadメソッドをご利用ください

2021-09-07 08:03 UTC, su8ru commented on src/libs/audio.ts
> +document.documentElement.addEventListener("click", init);
onload イベントは「ユーザーがサイトを操作した（クリック、タップ、キーを押すなど）」に含まれない気がします
once だけつけます

2021-09-07 08:04 UTC, su8ru commented on src/libs/audio.ts
> +      audio.play();
これどういうこと…？

2021-09-07 08:06 UTC, su8ru commented on src/components/ResultChip.tsx
> +            successAudio.currentTime = 0;
これ Media が再読み込みされちゃいませんか（自動再生権限の取り直しが必要になったりしない？）

2021-09-07 11:44 UTC, ibuki2003 commented on src/libs/audio.ts
> +      audio.play();
最初の再生がただのpreloadかと思った

2021-09-07 11:57 UTC, ibuki2003 commented on src/components/ResultChip.tsx
> +            successAudio.currentTime = 0;
Audioのinstance単位で許可されてるらしいし行けそうでは？(
https://qiita.com/pentamania/items/2c568a9ec52148bbfd08

2021-09-07 14:55 UTC, su8ru commented on src/components/ResultChip.tsx
> +            successAudio.currentTime = 0;
Safari 相手だし危ない橋を渡りたくないな……

2021-09-08 01:29 UTC, ibuki2003 approved these changes

2021-09-08 02:34 UTC, Takeno-hito approved these changes

2021-09-08 02:34 UTC, merged