#127 QRコードログイン
afes-website/cappuccino-app pull request #137
Opened 2021-09-07 15:14 UTC by Takeno-hito

まだやってないタスク
- [ ] QRコードを読み取ったあとの確認画面 ( @su8ru )

2021-09-08 17:43 UTC, su8ru requested changes

2021-09-08 17:43 UTC, su8ru commented on src/pages/LoginQR.tsx
> +                "QRコードが古い可能性があります。展示責任者から最新のQRコードを受け取って下さい。",
スペース有無統一（ここだけじゃない）

2021-09-08 17:43 UTC, su8ru commented on src/pages/LoginQR.tsx
> +                  "情報を取得できませんでした",
```suggestion
                  "情報を取得できませんでした。",
```

2021-09-08 17:43 UTC, su8ru commented on src/pages/LoginQR.tsx
> +            "読み取るQRコードが違う可能性があります。",
「誤った QR コードをスキャンしている可能性があります。」とかのほうがしっくりきませんか

2021-09-08 17:43 UTC, su8ru commented on src/pages/LoginQR.tsx
> +                "QRコードが古い可能性があります。展示責任者から最新のQRコードを受け取って下さい。",
展示責任者から受け取る…？
QR は展責に管理させて目の前でスキャンさせるイメージでいるので、「受け取る」は何かしらの誤解を招きそう

2021-09-09 14:10 UTC, Takeno-hito commented on src/pages/LoginQR.tsx
> +                "QRコードが古い可能性があります。展示責任者から最新のQRコードを受け取って下さい。",
展示責任者から提示された QR コードを使用してください？

2021-09-10 08:42 UTC, ibuki2003 requested changes
動作確認と日本語チェックはあんまりやってないです

2021-09-10 08:42 UTC, ibuki2003 commented on src/pages/LoginQR.tsx
> +const LoginQR: React.VFC = () => {
`QRLogin` とするか `LoginWithQR` とかするかしたい

2021-09-10 08:42 UTC, ibuki2003 commented on src/pages/LoginQR.tsx
> +  const [encoded, setEncoded] = useState("");
名前、lastか何か含められませんか encodedとしちゃうと中身しか説明してなくて用途が読めない

2021-09-10 08:42 UTC, ibuki2003 commented on src/pages/LoginQR.tsx
> +    if (data === null || encoded === data || checkStatus === "loading") return;
同一を蹴る処理、n箇所で見かけるけどQRScannerに突っ込みたくなりませんか

2021-09-10 08:42 UTC, ibuki2003 commented on src/pages/LoginQR.tsx
> +      if (typeof id === "string" && typeof pw === "string") {
早期return

2021-09-10 08:42 UTC, ibuki2003 commented on src/pages/LoginQR.tsx
> +              <Typography>ユーザーが見つかりませんでした。</Typography>
これになったとき操作できなくならん？(ログインキャンセルの遷移先がここじゃないあたりこっちも狙ってるのかな…?

2021-09-10 13:52 UTC, su8ru commented on src/pages/LoginQR.tsx
> +              <Typography>ユーザーが見つかりませんでした。</Typography>
NavBar に戻るボタンがあるから操作できなくなるわけではないのと、まあこの状況にはならないだろうという慢心です

2021-09-10 13:59 UTC, su8ru commented on src/pages/LoginQR.tsx
> +    if (data === null || encoded === data || checkStatus === "loading") return;
この PR でいいならやっちゃうけど

2021-09-10 14:00 UTC, ibuki2003 commented on src/pages/LoginQR.tsx
> +    if (data === null || encoded === data || checkStatus === "loading") return;
まあいいんじゃないかな おねがい

2021-09-10 15:58 UTC, su8ru approved these changes

2021-09-11 00:59 UTC, ibuki2003 approved these changes

2021-09-11 04:10 UTC, su8ru approved these changes

2021-09-11 04:18 UTC, su8ru approved these changes

2021-09-12 12:25 UTC, ibuki2003 approved these changes

2021-09-12 14:06 UTC, merged