#136 エラー時のダイアログを廃止しアラートに統一
afes-website/cappuccino-app pull request #145
Opened 2021-09-10 15:43 UTC by Takeno-hito

fix: #136
ErrorHandler のコードが凄かったので根本から書き直す事になりました
あと Dialog と Alert で表示を分ける理由も特になかったので Alert に統一しました

2021-09-10 16:01 UTC, su8ru requested changes
> サーバーエラーが発生しました。至急、総務局にお問い合わせください。
status: 404
Request failed with status code 404

2021-09-10 16:01 UTC, su8ru commented
あ、そういうことか

2021-09-10 16:04 UTC, su8ru requested changes
`useErrorHandler.ts` に rename して

2021-09-10 16:11 UTC, su8ru commented
> @su8ru 
> > サーバーエラーが発生しました。至急、総務局にお問い合わせください。
> > status: 404
> > Request failed with status code 404

back 側のバグでした
afes-website/cappuccino-back#49

2021-09-13 15:32 UTC, Takeno-hito commented
waiting for review

2021-09-13 15:51 UTC, ibuki2003 requested changes
CRってほどでもないけど

2021-09-13 15:51 UTC, ibuki2003 commented on src/libs/useErrorHandler.ts
> +    setErrorMessage([...errorMessageList[errorCode]]);
これ一回ぶちまけるのなんでですか

2021-09-13 15:51 UTC, ibuki2003 commented on src/libs/useErrorHandler.ts
> +  return [errorMessage, setErrorCode, setError];
今更という感じもあるけど名前付きのほうが呼ぶの楽じゃないかな(してない理由があったっけ) `[]`を`{}`にすればだいたい済むはずだけど面倒かったら言ってください 考えます

2021-09-13 16:02 UTC, su8ru commented on src/libs/useErrorHandler.ts
> +  return [errorMessage, setErrorCode, setError];
どっちでもいいけど、なんか hooks は配列を返すイメージがあるからこの仕様な気がする

個人的には `setErrorCode` と `setError` の順番を入れ替えて配列継続したい

2021-09-13 16:11 UTC, ibuki2003 commented on src/libs/useErrorHandler.ts
> +  return [errorMessage, setErrorCode, setError];
お気持ち論争は懲り懲りなので退きます 順番はおまかせする

2021-09-13 16:15 UTC, ibuki2003 submitted a review, later dismissed

2021-09-13 16:29 UTC, su8ru approved these changes

2021-09-13 16:33 UTC, ibuki2003 approved these changes

2021-09-13 16:33 UTC, merged