#218 check-in の UI 改善
afes-website/cappuccino-app pull request #227
Opened 2021-11-08 12:31 UTC by su8ru

close #218 

スキャンした予約のデジタルチケットが表示されるようにしました！！
あと保護者予約のときの目視チェックアラートや人数偽装にも対応しています！

その他ご意見ご感想ご要望お待ちしております

↓変更点がすべて詰まったスクリーンショット

![image](https://user-images.githubusercontent.com/33474143/140742271-ed753212-538f-47cf-97f5-2dfbee4e1837.png)

2021-11-08 12:58 UTC, ibuki2003 commented
保護者alertは視界塞ぐくらいしてもいいとおもいます

2021-11-09 12:22 UTC, Takeno-hito requested changes

2021-11-09 12:22 UTC, Takeno-hito commented on src/components/TicketHeader.tsx
> +          ? wristBandPaletteColor(rsv.term.guest_type, "light").dark
ダークテーマの時に、待機中に「文化祭入場券」の文字とアイコンが表示されちゃう

2021-11-09 12:22 UTC, Takeno-hito commented on src/components/TicketHeader.tsx
> +  return (
予約QRが読み込まれてない時のチケット表示が 読み込み中っぽくて結構気になります

2021-11-09 12:25 UTC, Takeno-hito commented on src/components/TicketHeader.tsx
> +  return (
デジタルチケットのタームが分からない時の灰色表示とか使うと結構良さげな気がします

2021-11-09 12:28 UTC, Takeno-hito reviewed
予約情報照会のところもチケットが出るとちょっとうれしいかなと思った 面倒じゃないなら用意しといて 無くても全然問題はない

2021-11-11 06:40 UTC, Takeno-hito approved these changes

2021-11-11 06:42 UTC, ibuki2003 approved these changes

2021-11-11 06:53 UTC, merged