#223 展示内満員時の表示
afes-website/cappuccino-app pull request #229
Opened 2021-11-09 10:52 UTC by Takeno-hito

resolve: #223
- feat: warning status color
- feat: warning alert when exhibition is full
- refactor: avoid to use warning checkStatus
- refactor: extract isFull and checkIsFull

2021-11-09 12:28 UTC, Takeno-hito reviewed
レビューお待ちしています (コメント先間違えた)

2021-11-09 12:31 UTC, su8ru requested changes

2021-11-09 12:31 UTC, su8ru commented on src/pages/exhibition/EnterScan.tsx
> +      handleSuccess={checkIsFull}
こんなことせずに↓でもいいんじゃない？
どっちでもいいと思うけど

```diff
         api(aspida)
           .guests._id(guestId)
           .enter.$post({
             headers: {
               Authorization: "bearer " + currentUser?.token,
             },
             body: {
               exhibition_id: currentUserId ?? "",
             },
           })
+          .then((guest) => {
+            checkIsFull();
+            return guest;
+          })
```

2021-11-09 12:31 UTC, su8ru commented on src/pages/exhibition/EnterScan.tsx
> +    const intervalId = setInterval(checkIsFull, 15000);
下の StayStatusCard と間隔が違うのが気になった
どちらも 15s で統一していいんじゃないか

2021-11-09 12:31 UTC, su8ru commented on src/pages/exhibition/EnterScan.tsx
> +      .map(([, value]) => value)
わたしのクソコードに引っ張られてたらごめん

```suggestion
    const sum = Object.values(status.count)
```

2021-11-09 12:31 UTC, su8ru commented on src/pages/exhibition/EnterScan.tsx
> +    return () => clearInterval(intervalId);
↓じゃない？と思ったけどわたしもこう書いてたので文句は言えない…
挙動としてはたぶん変わらない……はず……！

```suggestion
    return () => {
      clearInterval(intervalId)
    };
```

2021-11-09 12:44 UTC, Takeno-hito commented on src/pages/exhibition/EnterScan.tsx
> +    return () => clearInterval(intervalId);
別に変えなくてもいい？いいよね

2021-11-09 14:54 UTC, ibuki2003 requested changes

2021-11-09 14:54 UTC, ibuki2003 commented on src/pages/exhibition/EnterScan.tsx
> +    const status = await api(aspida)
エラーハンドリング
catch書いてエラーのときになにか別のことを書いたほうが良さそう オフラインであることを示すのかalert閉じるだけにするのか

2021-11-09 16:15 UTC, su8ru commented on src/pages/exhibition/EnterScan.tsx
> +    const status = await api(aspida)
これオフライン対応な気がするな　話が別

2021-11-09 16:15 UTC, su8ru commented on src/pages/exhibition/EnterScan.tsx
> +    const status = await api(aspida)
アラート閉じろ、というのはある

2021-11-10 00:06 UTC, ibuki2003 reviewed
promiseがメソッドチェーンに戻っててわろてる

2021-11-10 00:06 UTC, ibuki2003 commented on src/components/GuestScan.tsx
> +                  <Alert severity="warning">滞在人数の上限に達しました。</Alert>
自動リロードであることをちゃんと書きたい気がするんですがどうですかね
```suggestion
                  <Alert severity="warning">滞在人数の上限に達しました。空きができるまでそのままでお待ちください</Alert>
```
とかするかスピナーを置くか…?

2021-11-11 07:05 UTC, Takeno-hito commented on src/components/GuestScan.tsx
> +                  <Alert severity="warning">滞在人数の上限に達しました。</Alert>
スピナー置くのもちょっと鬱陶しい感じがするし、うーん
「現在展示内は満員です。」とかはどう

2021-11-12 14:32 UTC, Takeno-hito commented
たけのひと的 approved

2021-11-12 15:15 UTC, su8ru approved these changes

2021-11-12 15:32 UTC, merged